http://localhost:5000/api/match_predictions/15
########################


https://bet-app-livid.vercel.app/api/matches

########################

http://localhost:5000/api/predictions/2

########################

http://localhost:5000/api/points/12


########################



http://localhost:5000/api/matches

#########################

POST http://localhost:5000/api/login
Content-Type: application/json

{
  "login": "Kadeo",
  "password": "kadeo123"
}

#########################

POST http://localhost:5000/api/result
Content-Type: application/json
Authorization: jebackurwaXD

{
  "match_id": 54,
  "team_one_goals": 1,
  "team_two_goals": 2
}

########################

POST http://localhost:5000/api/predictions
Content-Type: application/json

{
  "match_id": 16,
  "user_id": 2,
  "team_one_goals": 2,
  "team_two_goals": 1,
  "result": 0
}

#######################
POST http://localhost:5000/api/matches
Content-Type: application/json
Authorization: jebackurwaXD

{
    "round" : "Matchday 4",
    "matches": [
        {
            "date": "2024-06-28",
            "time": "21:00:00",
            "team_one": "Belgia",
            "team_two": "Holandia",
            "group": "Group A"
        },
        {
            "date": "2024-06-29",
            "time": "21:30:00",
            "team_one": "Niemcy",
            "team_two": "Austria",
            "group": "Group B"

        },
        {
            "date": "2024-06-30",
            "time": "15:00:00",
            "team_one": "Francja",
            "team_two": "Anglia",
            "group": "Group C"
        }
    ]
}

#######################
POST http://localhost:5000/api/matches
Content-Type: application/json

{
    "name": "Euro 2024",
    "rounds": [
      {
        "name": "Matchday 1",
        "matches": [
          {
            "num": 1,
            "date": "2024-06-14",
            "time": "21:00",
            "team1": {
              "name": "Niemcy",
              "code": "GER"
            },
            "team2": {
              "name": "Szkocja",
              "code": "SCO"
            },
            "group": "Group A"
          },
          {
            "num": 2,
            "date": "2024-06-15",
            "time": "15:00",
            "team1": {
              "name": "Węgry",
              "code": "HUN"
            },
            "team2": {
              "name": "Szwajcaria",
              "code": "SUI"
            },
            "group": "Group A"
          },
          {
            "num": 7,
            "date": "2024-06-15",
            "time": "18:00",
            "team1": {
              "name": "Hiszpania",
              "code": "ESP"
            },
            "team2": {
              "name": "Chorwacja",
              "code": "CRO"
            },
            "group": "Group B"
          },
          {
            "num": 8,
            "date": "2024-06-15",
            "time": "21:00",
            "team1": {
              "name": "Włochy",
              "code": "ITA"
            },
            "team2": {
              "name": "Albania",
              "code": "ALB"
            },
            "group": "Group B"
          },
          {
            "num": 13,
            "date": "2024-06-16",
            "time": "18:00",
            "team1": {
              "name": "Słowenia",
              "code": "SVN"
            },
            "team2": {
              "name": "Dania",
              "code": "DEN"
            },
            "group": "Group C"
          },
          {
            "num": 14,
            "date": "2024-06-16",
            "time": "21:00",
            "team1": {
              "name": "Serbia",
              "code": "SRB"
            },
            "team2": {
              "name": "Anglia",
              "code": "ENG"
            },
            "group": "Group C"
          },
          {
            "num": 19,
            "date": "2024-06-16",
            "time": "15:00",
            "team1": {
              "name": "Polska",
              "code": "POL"
            },
            "team2": {
              "name": "Holandia",
              "code": "NED"
            },
            "group": "Group D"
          },
          {
            "num": 20,
            "date": "2024-06-17",
            "time": "21:00",
            "team1": {
              "name": "Austria",
              "code": "AUT"
            },
            "team2": {
              "name": "Francja",
              "code": "FRA"
            },
            "group": "Group D"
          },
          {
            "num": 25,
            "date": "2024-06-17",
            "time": "15:00",
            "team1": {
              "name": "Rumunia",
              "code": "ROU"
            },
            "team2": {
              "name": "Ukraina",
              "code": "UKR"
            },
            "group": "Group E"
          },
          {
            "num": 26,
            "date": "2024-06-17",
            "time": "18:00",
            "team1": {
              "name": "Belgia",
              "code": "BEL"
            },
            "team2": {
              "name": "Słowacja",
              "code": "SVK"
            },
            "group": "Group E"
          },
          {
            "num": 31,
            "date": "2024-06-18",
            "time": "18:00",
            "team1": {
              "name": "Turcja",
              "code": "TUR"
            },
            "team2": {
              "name": "Gruzja",
              "code": "GEO"
            },
            "group": "Group F"
          },
          {
            "num": 32,
            "date": "2024-06-18",
            "time": "21:00",
            "team1": {
              "name": "Portugalia",
              "code": "POR"
            },
            "team2": {
              "name": "Czechy",
              "code": "CZE"
            },
            "group": "Group F"
          }
        ]
      },
      {
        "name": "Matchday 2",
        "matches": [
          {
            "num": 3,
            "date": "2024-06-19",
            "time": "18:00",
            "team1": {
              "name": "Niemcy",
              "code": "GER"
            },
            "team2": {
              "name": "Węgry",
              "code": "HUN"
            },
            "group": "Group A"
          },
          {
            "num": 4,
            "date": "2024-06-19",
            "time": "21:00",
            "team1": {
              "name": "Szkocja",
              "code": "SCO"
            },
            "team2": {
              "name": "Szwajcaria",
              "code": "SUI"
            },
            "group": "Group A"
          },
          {
            "num": 9,
            "date": "2024-06-19",
            "time": "15:00",
            "team1": {
              "name": "Chorwacja",
              "code": "CRO"
            },
            "team2": {
              "name": "Albania",
              "code": "ALB"
            },
            "group": "Group B"
          },
          {
            "num": 10,
            "date": "2024-06-20",
            "time": "21:00",
            "team1": {
              "name": "Hiszpania",
              "code": "ESP"
            },
            "team2": {
              "name": "Włochy",
              "code": "ITA"
            },
            "group": "Group B"
          },
          {
            "num": 15,
            "date": "2024-06-20",
            "time": "15:00",
            "team1": {
              "name": "Słowenia",
              "code": "SVN"
            },
            "team2": {
              "name": "Serbia",
              "code": "SRB"
            },
            "group": "Group C"
          },
          {
            "num": 16,
            "date": "2024-06-20",
            "time": "18:00",
            "team1": {
              "name": "Dania",
              "code": "DEN"
            },
            "team2": {
              "name": "Anglia",
              "code": "ENG"
            },
            "group": "Group C"
          },
          {
            "num": 21,
            "date": "2024-06-21",
            "time": "18:00",
            "team1": {
              "name": "Polska",
              "code": "POL"
            },
            "team2": {
              "name": "Austria",
              "code": "AUT"
            },
            "group": "Group D"
          },
          {
            "num": 22,
            "date": "2024-06-21",
            "time": "21:00",
            "team1": {
              "name": "Holandia",
              "code": "NED"
            },
            "team2": {
              "name": "Francja",
              "code": "FRA"
            },
            "group": "Group D"
          },
          {
            "num": 27,
            "date": "2024-06-21",
            "time": "15:00",
            "team1": {
              "name": "Słowacja",
              "code": "SVK"
            },
            "team2": {
              "name": "Ukraina",
              "code": "UKR"
            },
            "group": "Group E"
          },
          {
            "num": 28,
            "date": "2024-06-22",
            "time": "21:00",
            "team1": {
              "name": "Belgia",
              "code": "BEL"
            },
            "team2": {
              "name": "Rumunia",
              "code": "ROU"
            },
            "group": "Group E"
          },
          {
            "num": 33,
            "date": "2024-06-22",
            "time": "15:00",
            "team1": {
              "name": "Gruzja",
              "code": "GEO"
            },
            "team2": {
              "name": "Czechy",
              "code": "CZE"
            },
            "group": "Group F"
          },
          {
            "num": 34,
            "date": "2024-06-22",
            "time": "18:00",
            "team1": {
              "name": "Turcja",
              "code": "TUR"
            },
            "team2": {
              "name": "Portugalia",
              "code": "POR"
            },
            "group": "Group F"
          }
        ]
      },
      {
        "name": "Matchday 3",
        "matches": [
          {
            "num": 5,
            "date": "2024-06-23",
            "time": "21:00",
            "team1": {
              "name": "Szwajcaria",
              "code": "SUI"
            },
            "team2": {
              "name": "Niemcy",
              "code": "GER"
            },
            "group": "Group A"
          },
          {
            "num": 6,
            "date": "2024-06-23",
            "time": "21:00",
            "team1": {
              "name": "Szkocja",
              "code": "SCO"
            },
            "team2": {
              "name": "Węgry",
              "code": "HUN"
            },
            "group": "Group A"
          },
          {
            "num": 11,
            "date": "2024-06-24",
            "time": "21:00",
            "team1": {
              "name": "Albania",
              "code": "ALB"
            },
            "team2": {
              "name": "Hiszpania",
              "code": "ESP"
            },
            "group": "Group B"
          },
          {
            "num": 12,
            "date": "2024-06-24",
            "time": "21:00",
            "team1": {
              "name": "Chorwacja",
              "code": "CRO"
            },
            "team2": {
              "name": "Włochy",
              "code": "ITA"
            },
            "group": "Group B"
          },
          {
            "num": 17,
            "date": "2024-06-25",
            "time": "21:00",
            "team1": {
              "name": "Anglia",
              "code": "ENG"
            },
            "team2": {
              "name": "Słowenia",
              "code": "SVN"
            },
            "group": "Group C"
          },
          {
            "num": 18,
            "date": "2024-06-25",
            "time": "21:00",
            "team1": {
              "name": "Dania",
              "code": "DEN"
            },
            "team2": {
              "name": "Serbia",
              "code": "SRB"
            },
            "group": "Group C"
          },
          {
            "num": 23,
            "date": "2024-06-25",
            "time": "18:00",
            "team1": {
              "name": "Holandia",
              "code": "NED"
            },
            "team2": {
              "name": "Austria",
              "code": "AUT"
            },
            "group": "Group D"
          },
          {
            "num": 24,
            "date": "2024-06-25",
            "time": "18:00",
            "team1": {
              "name": "Francja",
              "code": "FRA"
            },
            "team2": {
              "name": "Polska",
              "code": "POL"
            },
            "group": "Group D"
          },
          {
            "num": 29,
            "date": "2024-06-26",
            "time": "18:00",
            "team1": {
              "name": "Słowacja",
              "code": "SVK"
            },
            "team2": {
              "name": "Rumunia",
              "code": "ROU"
            },
            "group": "Group E"
          },
          {
            "num": 30,
            "date": "2024-06-26",
            "time": "18:00",
            "team1": {
              "name": "Ukraina",
              "code": "UKR"
            },
            "team2": {
              "name": "Belgia",
              "code": "BEL"
            },
            "group": "Group E"
          },
          {
            "num": 35,
            "date": "2024-06-26",
            "time": "21:00",
            "team1": {
              "name": "Gruzja",
              "code": "GEO"
            },
            "team2": {
              "name": "Portugalia",
              "code": "POR"
            },
            "group": "Group F"
          },
          {
            "num": 36,
            "date": "2024-06-26",
            "time": "21:00",
            "team1": {
              "name": "Czechy",
              "code": "CZE"
            },
            "team2": {
              "name": "Turcja",
              "code": "TUR"
            },
            "group": "Group F"
          }
        ]
      }
    ]
  }


#######################
POST http://localhost:5000/api/teams
Content-Type: application/json

[
  {
    "grupa": "A",
    "drużyny": [
      "Niemcy",
      "Węgry",
      "Szkocja",
      "Szwajcaria"
    ]
  },
  {
    "grupa": "B",
    "drużyny": [
      "Hiszpania",
      "Chorwacja",
      "Włochy",
      "Albania"
    ]
  },
  {
    "grupa": "C",
    "drużyny": [
      "Słowenia",
      "Dania",
      "Serbia",
      "Anglia"
    ]
  },
  {
    "grupa": "D",
    "drużyny": [
      "Polska",
      "Holandia",
      "Austria",
      "Francja"
    ]
  },
  {
    "grupa": "E",
    "drużyny": [
      "Belgia",
      "Słowacja",
      "Rumunia",
      "Ukraina"
    ]
  },
  {
    "grupa": "F",
    "drużyny": [
      "Turcja",
      "Gruzja",
      "Portugaliaia",
      "Czechy"
    ]
  }
]
